export enum AdminPermissions {
  MANAGE_USERS = 'MANAGE_USERS',
  MANAGE_FINANCE = 'MANAGE_FINANCE',
  MANAGE_BOOKS = 'MANAGE_BOOKS',
  MANAGE_STAFF = 'MANAGE_STAFF',
  MANAGE_NOTIFICATIONS = 'MANAGE_NOTIFICATIONS',
}
