export enum AuditAction {
    BOOK_CREATED = 'BOOK_CREATED',
    BOOK_UPDATED = 'BOOK_UPDATED',
    BOOK_DELETED = 'BOOK_DELETED',
    BOOK_TYPE_CREATED = 'BOOK_TYPE_CREATED',
    BOOK_TYPE_UPDATED = 'BOOK_TYPE_UPDATED',
    BOOK_TYPE_DELETED = 'BOOK_TYPE_DELETED',
    CHAPTER_CREATED = 'CHAPTER_CREATED',
    CHAPTER_UPDATED = 'CHAPTER_UPDATED',
    CHAPTER_DELETED = 'CHAPTER_DELETED',
    GENRE_CREATED = 'GENRE_CREATED',
    GENRE_UPDATED = 'GENRE_UPDATED',
    GENRE_DELETED = 'GENRE_DELETED',
    CONTRIBUTOR_CREATED = 'CONTRIBUTOR_CREATED',
    CONTRIBUTOR_UPDATED = 'CONTRIBUTOR_UPDATED',
    CONTRIBUTOR_DELETED = 'CONTRIBUTOR_DELETED',
    USER_UPDATED = 'USER_UPDATED',
    USER_BANNED = 'USER_BANNED',
    USER_UNBANNED = 'USER_UNBANNED',
    USER_PERMISSIONS_UPDATED = 'USER_PERMISSIONS_UPDATED',
    BALANCE_CREDIT = 'BALANCE_CREDIT',
    BALANCE_DEBIT = 'BALANCE_DEBIT',
    STAFF_CREATED = 'STAFF_CREATED',
    STAFF_UPDATED = 'STAFF_UPDATED',
    STAFF_DELETED = 'STAFF_DELETED',
    SETTINGS_UPDATED = 'SETTINGS_UPDATED',
    BROADCAST_SENT = 'BROADCAST_SENT',
    MEDIA_UPLOADED = 'MEDIA_UPLOADED',
    MEDIA_UPDATED = 'MEDIA_UPDATED',
    MEDIA_DELETED = 'MEDIA_DELETED',
    COLLECTION_CREATED = 'COLLECTION_CREATED',
    COLLECTION_UPDATED = 'COLLECTION_UPDATED',
    COLLECTION_DELETED = 'COLLECTION_DELETED',
}

export enum AuditCategory {
    CONTENT = 'CONTENT',
    USER = 'USER',
    STAFF = 'STAFF',
    FINANCE = 'FINANCE',
    SYSTEM = 'SYSTEM',
    SECURITY = 'SECURITY',
}

export enum AuditSeverity {
    LOW = 'LOW',
    MEDIUM = 'MEDIUM',
    HIGH = 'HIGH',
    CRITICAL = 'CRITICAL',
    INFO = 'INFO',
    WARNING = 'WARNING',
}

export const AUDIT_ACTION_VALUES = Object.values(AuditAction);
export const AUDIT_CATEGORY_VALUES = Object.values(AuditCategory);
export const AUDIT_SEVERITY_VALUES = Object.values(AuditSeverity);