export enum AuditAction {
  BOOK_CREATED = 'BOOK_CREATED', BOOK_UPDATED = 'BOOK_UPDATED', BOOK_DELETED = 'BOOK_DELETED',
  CHAPTER_CREATED = 'CHAPTER_CREATED', CHAPTER_UPDATED = 'CHAPTER_UPDATED', CHAPTER_DELETED = 'CHAPTER_DELETED',
  GENRE_CREATED = 'GENRE_CREATED', GENRE_UPDATED = 'GENRE_UPDATED', GENRE_DELETED = 'GENRE_DELETED',
  AUTHOR_CREATED = 'AUTHOR_CREATED', AUTHOR_UPDATED = 'AUTHOR_UPDATED', AUTHOR_DELETED = 'AUTHOR_DELETED',
  CONTRIBUTOR_CREATED = 'CONTRIBUTOR_CREATED', CONTRIBUTOR_UPDATED = 'CONTRIBUTOR_UPDATED', CONTRIBUTOR_DELETED = 'CONTRIBUTOR_DELETED',
  USER_BANNED = 'USER_BANNED', USER_UNBANNED = 'USER_UNBANNED', PREMIUM_GRANTED = 'PREMIUM_GRANTED', PREMIUM_REMOVED = 'PREMIUM_REMOVED',
  STAFF_CREATED = 'STAFF_CREATED', STAFF_UPDATED = 'STAFF_UPDATED', STAFF_DELETED = 'STAFF_DELETED',
  SETTINGS_UPDATED = 'SETTINGS_UPDATED', BROADCAST_SENT = 'BROADCAST_SENT', MEDIA_UPLOADED = 'MEDIA_UPLOADED', MEDIA_DELETED = 'MEDIA_DELETED',
}

export enum AuditCategory { CONTENT = 'CONTENT', USER = 'USER', STAFF = 'STAFF', FINANCE = 'FINANCE', SYSTEM = 'SYSTEM', SECURITY = 'SECURITY' }
export enum AuditSeverity { INFO = 'INFO', WARNING = 'WARNING', CRITICAL = 'CRITICAL' }
export const AUDIT_LOG_CACHE_VERSION_KEY = 'audit_log:version';
export const AUDIT_LOG_METADATA_KEY = Symbol('AUDIT_LOG_METADATA');
