export const POPULARITY_GLOBAL_MEAN = 3.8;
export const POPULARITY_MIN_VOTES = 10;

export const RELATED_MAX_FRESHNESS_DAYS = 180;

export const RELATED_GENRE_WEIGHT = 65;
export const RELATED_TYPE_WEIGHT = 15;
export const RELATED_POPULARITY_WEIGHT = 15;
export const RELATED_FRESHNESS_WEIGHT = 5;
export const RELATED_EXPONENTIAL_DECAY_LAMBDA = 0.012;
