import type { IconKey } from '@readory/shared';
import type { LucideIcon } from 'lucide-react';
import {
  Bell,
  BookMarked,
  BookOpen,
  CalendarRange,
  Compass,
  Edit,
  Eraser,
  Feather,
  FileImage,
  Flame,
  Ghost,
  Globe,
  GraduationCap,
  Grid2x2,
  Heart,
  HeartCrack,
  Home,
  Languages,
  Laugh,
  LayoutDashboard,
  Library,
  MessageCircleHeartIcon,
  Palette,
  Pen,
  PenLine,
  RefreshCcw,
  Rocket,
  ScrollText,
  Search,
  Shield,
  Skull,
  Sparkles,
  Sword,
  Swords,
  Type,
  UserCheck,
  Volleyball,
  Wallet,
  Wand2,
  Watch,
} from 'lucide-react';

export const iconRegistry: Record<IconKey, LucideIcon> = {
  manga: BookMarked,
  manhwa: Sparkles,
  comic: ScrollText,
  novel: Feather,
  lightNovel: PenLine,
  shield: Shield,
  action: Swords,
  adventure: Compass,
  romance: Heart,
  horror: Ghost,
  comedy: Laugh,
  fantasy: Wand2,
  thriller: Skull,
  drama: Flame,
  'sci-fi': Globe,
  home: Home,
  bookOpen: BookOpen,
  library: Library,
  layoutDashboard: LayoutDashboard,
  timeTravel: Watch,
  sports: Volleyball,
  schoolLife: GraduationCap,
  isekai: Rocket,
  mystery: Search,
  reincarnation: RefreshCcw,
  shoujo: MessageCircleHeartIcon,
  shounen: Sword,
  tragedy: HeartCrack,
  sliceOfLife: CalendarRange,
  wallet: Wallet,
  author: Pen,
  translator: Languages,
  illustrator: Palette,
  editor: Edit,
  cleaner: Eraser,
  typesetter: Type,
  rawProvider: FileImage,
  supervisor: UserCheck,
  collections: Grid2x2,
  notifications: Bell,
} as const;
